- name: Install any necessary dependency
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Import InfluxData GPG signing key
  apt_key:
    state: present
    id: D8FF8E1F7DF8B07E
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    keyring: /usr/share/keyrings/influxdata-archive_compat.key
  become: yes

- name: Add InfluxData repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/influxdata-archive_compat.key] https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ influxdb_repository_channel }}
    state: present

- name: Install InfluxDB package
  apt:
    name: influxdb
    state: present
    update_cache: yes
    cache_valid_time: 3600
