---
- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Download version
  get_url:
    url: "{{ influxdb_dl_url }}"
    dest: "{{ influxdb_pkg }}"
    checksum: "md5:{{ influxdb_md5_checksum }}"
  tags:
    - influxdb

- name: Install package
  command: "dpkg --skip-same-version -i {{ influxdb_pkg }}"
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  when: ansible_distribution in ['Ubuntu', 'Debian']
  tags:
    - influxdb
